import json
import os
import matplotlib.pyplot as plt
import numpy as np

def load_rewards(filepath):
    try:
        with open(filepath, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        return []

def plot_results():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    results_dir = os.path.join(base_dir, 'results')
    
    lstm_rewards = load_rewards(os.path.join(results_dir, 'baseline_lstm_rewards.json'))
    transformer_rewards = load_rewards(os.path.join(results_dir, 'baseline_transformer_rewards.json'))
    d3qn_data = load_rewards(os.path.join(results_dir, 'improved_d3qn_rewards.json'))
    
    # Handle dict vs list format
    if isinstance(d3qn_data, dict) and 'rewards' in d3qn_data:
        d3qn_rewards = d3qn_data['rewards']
    else:
        d3qn_rewards = d3qn_data
        
    # Same for LSTM (it might be a dict now if generated by the new script)
    if isinstance(lstm_rewards, dict) and 'rewards' in lstm_rewards:
        lstm_rewards = lstm_rewards['rewards']

    plt.figure(figsize=(10, 6))

    def rolling_avg(data, window=50):
        if not data or len(data) < window: return data
        return np.convolve(data, np.ones(window)/window, mode='valid')

    if lstm_rewards:
        plt.plot(rolling_avg(lstm_rewards), label='Baseline LSTM', color='teal', alpha=0.8)
    if transformer_rewards:
        plt.plot(rolling_avg(transformer_rewards), label='Baseline DistilBERT', color='purple', linestyle='--', alpha=0.5)
    if d3qn_rewards:
        plt.plot(rolling_avg(d3qn_rewards), label='Improved D3QN (DistilBERT)', color='red', linewidth=2)

    plt.title('Training Performance in Cooking World (Rolling Avg)')
    plt.xlabel('Episode')
    plt.ylabel('Total Reward')
    plt.legend()
    plt.grid(True, alpha=0.3)
    
    out_path = os.path.join(results_dir, 'comparison_plot.png')
    plt.savefig(out_path)
    print(f"Plot saved to {out_path}")

if __name__ == "__main__":
    plot_results()
